baseurl = "https://translations.headsalon.org/"
languageCode = "zh-CN"
title = "海德沙龙·翻译组"
theme = "hugo-xmag"
googleAnalytics = "UA-112412926-1"
disqusShortname = "headsalonfanyizu"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 12

[permalinks]
    post = "/post/:year/:month/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "我们是一群搬砖工，负责将英文世界的好文章搬进中文世界"
    summary_length = 300
    github_edit = "https://github.com/headsalon/fanyizu/edit/master/content/"
    footer = "&copy; [海德沙龙](https://headsalon.org/) | [微博](https://weibo.com/headsalon) | [公众号](/about)"

[params.text]
    back = "&larr; 返回首页"
    edit = "编辑本页 &rarr;"
    truncated = "&hellip;&hellip;"
    tags = "关键词："
    comment = "发表/查看评论"
    plot_maker = "制图"
    proof_reader = "校对"
    second_proof_reader = "二校"
    translator = "翻译"
    link = "网址"
    writing_time = "写作时间"
    source = "来源"
    author = "作者"
    editor = "译文编辑"
    original_editor = "原文编辑"
    description = "原始点评"
    more_description = "后续点评"
    contributors_included = "正文是否已包含‘编辑’等信息"

